import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
import { cookies } from 'next/headers'
import Navbar from './components/Navbar';
import LightAndDarkModeSwitch from "./components/LightAndDarkModeSwitch";
import ThemeProvider from "./components/ThemeProvider";
import NoFlashOfIncorrectTheme from "./components/NoFlashOfIncorrectTheme";
import Auth0ClientProvider from './components/Auth0ClientProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read theme cookie on the server so SSR can render with the user's chosen theme
  const cookieStore = await cookies()
  const themeCookie = cookieStore.get ? cookieStore.get('theme') : undefined
  const initialTheme = themeCookie ? themeCookie.value : undefined
  return (
  <html lang="en" className={`theme-transition-disable ${initialTheme ?? ''}`} data-theme={initialTheme ?? undefined}>
      <head>
        <Script id="theme" strategy="beforeInteractive">
          {`(function() {
              // If server already provided a data-theme, don't override it on the client.
              try {
                var existing = document.documentElement.getAttribute('data-theme')
                if (existing) return
              } catch (e) {}

              // Helper to read a cookie value by name
              function readCookie(name) {
                try {
                  var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'))
                  if (match) return decodeURIComponent(match[2])
                } catch (e) {}
                return null
              }

              function getInitialTheme() {
                // 1) Prefer cookie set by our app (synchronous and survives redirects)
                try {
                  var cookieTheme = readCookie('theme')
                  if (cookieTheme === 'light' || cookieTheme === 'dark') return cookieTheme
                } catch (e) {}

                // 2) Then try localStorage
                try {
                  var persistedTheme = localStorage.getItem('theme')
                  if (persistedTheme === 'light' || persistedTheme === 'dark') return persistedTheme
                } catch (e) {}

                // 3) Finally fall back to system preference
                try {
                  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
                } catch (e) {
                  return 'light'
                }
              }

              var theme = getInitialTheme()
              document.documentElement.classList.add(theme)
              document.documentElement.setAttribute('data-theme', theme)
            })()`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NoFlashOfIncorrectTheme />
        <ThemeProvider>
          <Auth0ClientProvider>
          {/* Use an app-root container that spans the viewport height; make content area grow and scroll internally */}
          <div className="app-root">
            <div className="flex flex-1">
              <Navbar />
              <div className="flex flex-col flex-1 p-2 overflow-auto">
                <div className="flex justify-end mb-4">
                  <LightAndDarkModeSwitch />
                </div>
                <main className="flex-1">{children}</main>
              </div>
            </div>
          </div>
          </Auth0ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
